"""Home Assistant add-on entry point (`os2slice-addon`), D-12 / D-17.

The Supervisor writes the add-on's Configuration tab to /data/options.json.
This renders that into os2slice's config file (regenerated on every start,
never edited by hand), puts the keys into the environment (never on disk
outside /data, never in logs), prints `doctor`, then runs `serve`.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path
from typing import Any

OPTIONS = Path("/data/options.json")
DATA = Path("/data")
SSL = Path("/ssl")
PORT = 8443  # inside the container; the host port is set on the add-on's Network tab
SECRET_OPTIONS = {  # option -> environment variable, by [onshape] auth mode (D-23)
    "keys": {
        "onshape_access_key": "ONSHAPE_ACCESS_KEY",
        "onshape_secret_key": "ONSHAPE_SECRET_KEY",
        "bambuddy_api_key": "BAMBUDDY_API_KEY",
    },
    "oauth": {
        "onshape_oauth_client_secret": "ONSHAPE_OAUTH_CLIENT_SECRET",
        "bambuddy_api_key": "BAMBUDDY_API_KEY",
    },
}


class OptionsError(Exception):
    pass


def render_config(opts: dict[str, Any], ssl_dir: Path = SSL) -> str:
    """Build config.toml text from the add-on options (validated again by config.parse)."""

    def s(v: object) -> str:  # TOML basic string; JSON escaping is valid TOML
        return json.dumps(str(v))

    hosts = opts.get("hosts") or []
    if not hosts:
        raise OptionsError("Set 'hosts', e.g. print.example.duckdns.org:8443")
    mode = opts.get("onshape_auth") or "keys"
    onshape = [f"auth = {s(mode)}"]
    if mode == "oauth":
        onshape.append(f"oauth_client_id = {s(opts.get('onshape_oauth_client_id', ''))}")
    lines = [
        "# Generated by the os2slice add-on from its Configuration tab. Edits are overwritten.",
        "",
        "[onshape]",
        *onshape,
        "",
        "[server]",
        'identity = "lan"',
        'bind = "0.0.0.0"',
        f"port = {PORT}",
        f"hosts = [{', '.join(s(h) for h in hosts)}]",
        f"tls_cert = {s(ssl_dir / opts.get('certfile', 'fullchain.pem'))}",
        f"tls_key = {s(ssl_dir / opts.get('keyfile', 'privkey.pem'))}",
        "",
        "[bambuddy]",
        f"base_url = {s(opts.get('bambuddy_url', 'http://172.30.32.1:8000'))}",
        f"folder = {s(opts.get('library_folder', 'Onshape'))}",
        *(
            [f"public_url = {s(opts['bambuddy_public_url'])}"]
            if opts.get("bambuddy_public_url")
            else []
        ),
        f"default_printer = {s(opts.get('default_printer', ''))}",
        f"manual_start = {'true' if opts.get('manual_start', True) else 'false'}",
        "",
    ]
    for preset in opts.get("presets") or []:
        lines += [
            f"[bambuddy.presets.{s(preset['model'])}]",
            f"printer = {s(preset['printer'])}",
            f"process = {s(preset['process'])}",
            f"filament = {s(preset['filament'])}",
            *([f"bed_type = {s(preset['bed_type'])}"] if preset.get("bed_type") else []),
            "",
        ]
    lines += [
        *(
            [
                "[web_studio]",
                f"url = {s(opts['web_studio_url'])}",
                'inbox = "/share/os2slice/inbox"',
                'status = "/share/os2slice/web-studio.json"',
                "",
            ]
            if opts.get("web_studio_url")
            else []
        ),
        "[print_defaults]",
        f"walls = {int(opts.get('walls', 2))}",
        f"infill = {int(opts.get('infill', 15))}",
        f"supports = {s(opts.get('supports', 'off'))}",
        f"build_plate_only = {'true' if opts.get('build_plate_only') else 'false'}",
        *([f"bed_type = {s(opts['default_plate'])}"] if opts.get("default_plate") else []),
        "",
    ]
    return "\n".join(lines)


def prepare(opts: dict[str, Any], data: Path = DATA, ssl_dir: Path = SSL) -> Path:
    """Write the config, set up the environment; returns the config path."""
    mode = opts.get("onshape_auth") or "keys"
    if mode not in SECRET_OPTIONS:
        raise OptionsError("onshape_auth must be keys or oauth")
    needed = SECRET_OPTIONS[mode]
    if mode == "oauth" and not str(opts.get("onshape_oauth_client_id", "")).strip():
        needed = {"onshape_oauth_client_id": "", **needed}
    missing = [k for k in needed if not str(opts.get(k, "")).strip()]
    if missing:
        raise OptionsError(f"Fill in {', '.join(missing)} on the add-on's Configuration tab")
    for option, env in SECRET_OPTIONS[mode].items():
        os.environ[env] = str(opts[option]).strip()
    os.environ["XDG_CONFIG_HOME"] = str(data)
    os.environ["XDG_STATE_HOME"] = str(data / "state")
    os.environ.setdefault("PYTHON_KEYRING_BACKEND", "keyring.backends.null.Keyring")
    os.environ["OS2SLICE_ADDON"] = "1"
    path = data / "os2slice" / "config.toml"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_config(opts, ssl_dir), encoding="utf-8")
    return path


def main() -> int:
    try:
        opts = json.loads(OPTIONS.read_text(encoding="utf-8"))
        prepare(opts)
    except (OSError, ValueError, KeyError, OptionsError) as e:
        print(f"os2slice add-on: {e}", file=sys.stderr, flush=True)
        return 1

    from os2slice import cli

    verbose = ["-v"] if opts.get("log_level") == "debug" else []
    cli.main([*verbose, "doctor"])  # the pass/fail table goes to the add-on log
    return cli.main([*verbose, "serve"])


if __name__ == "__main__":
    sys.exit(main())
