"""Home Assistant add-on entry point (`os2slice-addon`), D-12 / D-17 / D-28.

The Supervisor writes the add-on's Configuration tab to /data/options.json. At every
start this sets up, in order:

- **Secrets.** A non-empty secret option is exported to the environment (never written
  to config.toml, never logged) and the same entries are deleted from the secret file
  `/data/state/os2slice/secrets.json`, so the option wins. An empty option leaves that
  secret to the file, which is where the config page `/admin` saves secrets (see `auth`
  for the lookup order). A secret the `onshape_auth` mode needs that is in neither
  place is an options error.
- **admin_password.** When set, it is hashed into `/data/state/os2slice/admin.json`,
  but only when it differs from the stored one, so admin sessions survive a restart.
  When empty, a password set earlier keeps working. The password itself is never
  logged, written anywhere else or put in the environment.
- **config.toml** (`/data/os2slice/config.toml`). Rendered from the options only when
  it must be: when the file doesn't exist, when the rendered text differs from the
  last render (its sha256 is kept in `options.sha256` beside the file: the options
  changed, or a new add-on version renders differently), or when `reset_config` is on.
  Otherwise the file is kept as it is, with any edits made on `/admin`.

Every option is checked before anything is changed. Then it prints `doctor` and runs
`serve`.
"""

from __future__ import annotations

import hashlib
import json
import os
import sys
from collections.abc import Callable
from pathlib import Path
from typing import Any

from os2slice import auth
from os2slice.adminauth import AdminStore, PasswordError, check_rules
from os2slice.tomlwrite import write_atomic

OPTIONS = Path("/data/options.json")
DATA = Path("/data")
SSL = Path("/ssl")
PORT = 8443  # inside the container; the host port is set on the add-on's Network tab
REDIRECT_PORT = 8080  # plain HTTP, only 303s to https://<hosts[0]>/admin (Open Web UI)
SECRET_OPTIONS = {  # option -> environment variable, by [onshape] auth mode (D-23)
    "keys": {
        "onshape_access_key": "ONSHAPE_ACCESS_KEY",
        "onshape_secret_key": "ONSHAPE_SECRET_KEY",
        "bambuddy_api_key": "BAMBUDDY_API_KEY",
    },
    "oauth": {
        "onshape_oauth_client_secret": "ONSHAPE_OAUTH_CLIENT_SECRET",
        "bambuddy_api_key": "BAMBUDDY_API_KEY",
    },
}
# Secret option -> the entries in the secret file it stands for (and replaces).
SECRET_ENTRIES = {
    "onshape_access_key": (auth.ACCESS_ENTRY,),
    "onshape_secret_key": (auth.SECRET_ENTRY,),
    "onshape_oauth_client_secret": (auth.OAUTH_SECRET_ENTRY,),
    "bambuddy_api_key": (auth.BAMBUDDY_SECRET, auth.BAMBUDDY_ENTRY),
}
PAIRED = (("onshape_access_key", "onshape_secret_key"),)  # both filled in, or both empty
CONFIG_STAMP = "options.sha256"
HEADER = (
    "# Generated by the os2slice add-on from its Configuration tab. Edits made on the\n"
    "# config page /admin persist across restarts until those options change (or\n"
    "# reset_config is turned on); then this file is written again from the options."
)


class OptionsError(Exception):
    pass


def _say(line: str) -> None:
    print(f"os2slice add-on: {line}", flush=True)


def state_path(data: Path = DATA) -> Path:
    """The service's state dir inside the add-on (XDG_STATE_HOME = /data/state)."""
    return data / "state" / "os2slice"


def render_config(opts: dict[str, Any], ssl_dir: Path = SSL) -> str:
    """Build config.toml text from the add-on options (validated again by config.parse)."""

    def s(v: object) -> str:  # TOML basic string; JSON escaping is valid TOML
        return json.dumps(str(v))

    hosts = opts.get("hosts") or []
    if not hosts:
        raise OptionsError("Set 'hosts', e.g. print.example.duckdns.org:8443")
    mode = opts.get("onshape_auth") or "keys"
    onshape = [f"auth = {s(mode)}"]
    if mode == "oauth":
        onshape.append(f"oauth_client_id = {s(opts.get('onshape_oauth_client_id', ''))}")
    lines = [
        HEADER,
        "",
        "[onshape]",
        *onshape,
        "",
        "[server]",
        'identity = "lan"',
        'bind = "0.0.0.0"',
        f"port = {PORT}",
        f"hosts = [{', '.join(s(h) for h in hosts)}]",
        f"tls_cert = {s(ssl_dir / opts.get('certfile', 'fullchain.pem'))}",
        f"tls_key = {s(ssl_dir / opts.get('keyfile', 'privkey.pem'))}",
        "",
        "[bambuddy]",
        f"base_url = {s(opts.get('bambuddy_url', 'http://172.30.32.1:8000'))}",
        f"folder = {s(opts.get('library_folder', 'Onshape'))}",
        *(
            [f"public_url = {s(opts['bambuddy_public_url'])}"]
            if opts.get("bambuddy_public_url")
            else []
        ),
        f"default_printer = {s(opts.get('default_printer', ''))}",
        # Deprecated, no effect (the person printing chooses Wait for Start). Still
        # rendered so the output stays byte-identical for the same options.
        f"manual_start = {'true' if opts.get('manual_start', False) else 'false'}",
        "",
    ]
    for preset in opts.get("presets") or []:
        lines += [
            f"[bambuddy.presets.{s(preset['model'])}]",
            f"printer = {s(preset['printer'])}",
            f"process = {s(preset['process'])}",
            f"filament = {s(preset['filament'])}",
            *([f"bed_type = {s(preset['bed_type'])}"] if preset.get("bed_type") else []),
            "",
        ]
    lines += [
        *(
            [
                "[web_studio]",
                f"url = {s(opts['web_studio_url'])}",
                'inbox = "/share/os2slice/inbox"',
                'status = "/share/os2slice/web-studio.json"',
                "",
            ]
            if opts.get("web_studio_url")
            else []
        ),
        "[print_defaults]",
        f"walls = {int(opts.get('walls', 2))}",
        f"infill = {int(opts.get('infill', 15))}",
        f"supports = {s(opts.get('supports', 'off'))}",
        f"build_plate_only = {'true' if opts.get('build_plate_only') else 'false'}",
        f"top_layers = {int(opts.get('top_layers', 5))}",
        f"bottom_layers = {int(opts.get('bottom_layers', 3))}",
        f"brim = {'true' if opts.get('brim') else 'false'}",
        f"copies = {int(opts.get('copies', 1))}",
        *([f"bed_type = {s(opts['default_plate'])}"] if opts.get("default_plate") else []),
        "",
    ]
    return "\n".join(lines)


def _secret_groups(mode: str) -> list[tuple[str, ...]]:
    options = SECRET_OPTIONS[mode]
    paired = [g for g in PAIRED if all(o in options for o in g)]
    return paired + [(o,) for o in options if not any(o in g for g in paired)]


def _check_secrets(opts: dict[str, Any], mode: str, secrets: auth.SecretFile) -> list[str]:
    """The secret options that are filled in. Raises when a needed secret is nowhere."""
    filled = [o for o in SECRET_OPTIONS[mode] if str(opts.get(o) or "").strip()]
    missing: list[str] = []
    for group in _secret_groups(mode):
        if all(o in filled for o in group):
            continue
        if any(o in filled for o in group):  # half a key pair: both, or neither
            missing += [o for o in group if o not in filled]
        elif not all(secrets.get(*SECRET_ENTRIES[o]) for o in group):  # nor saved on /admin
            missing += group
    if missing:
        raise OptionsError(f"Fill in {', '.join(missing)} on the add-on's Configuration tab")
    return filled


def _check_admin_password(opts: dict[str, Any]) -> str:
    password = opts.get("admin_password") or ""
    if not isinstance(password, str):
        raise OptionsError("admin_password must be text")
    if password:
        try:
            check_rules(password)
        except PasswordError as e:  # the message never contains the password
            raise OptionsError(
                f"admin_password: {e}. Enter a longer one on the add-on's Configuration "
                "tab, or clear it to keep the config page /admin off"
            ) from None
    return password


def _apply_admin_password(password: str, path: Path, say: Callable[[str], None]) -> None:
    store = AdminStore(path)
    if password:
        if not store.verify(password):  # unchanged: keep the hash and the admin sessions
            store.set_password(password)
            say("admin password set from the admin_password option; /admin is on")
    elif not store.has_password():
        say("the config page /admin is off until admin_password is set")


def _write_config(text: str, path: Path, reset: bool, say: Callable[[str], None]) -> None:
    """Write config.toml from the options only when it must be (module docstring)."""
    stamp = path.with_name(CONFIG_STAMP)
    digest = hashlib.sha256(text.encode("utf-8")).hexdigest()
    try:
        last = stamp.read_text(encoding="utf-8").strip()
    except OSError:
        last = ""
    if reset:
        why = "reset_config is on"
    elif not path.exists():
        why = "there was none"
    elif last != digest:
        why = "the options changed"
    else:
        say(f"options unchanged; keeping {path} with any edits made on /admin")
        return
    write_atomic(path, text, mode=0o600)
    write_atomic(stamp, digest + "\n", mode=0o600)
    say(f"wrote {path} from the options ({why})")
    if reset:
        say("turn reset_config off again, or /admin edits are replaced at every start")


def prepare(
    opts: dict[str, Any],
    data: Path = DATA,
    ssl_dir: Path = SSL,
    say: Callable[[str], None] = _say,
) -> Path:
    """Check the options, then set up secrets, the admin password and the config file.

    Returns the config path. A bad option raises `OptionsError` before anything changes.
    """
    mode = opts.get("onshape_auth") or "keys"
    if mode not in SECRET_OPTIONS:
        raise OptionsError("onshape_auth must be keys or oauth")
    if mode == "oauth" and not str(opts.get("onshape_oauth_client_id", "")).strip():
        raise OptionsError("Fill in onshape_oauth_client_id on the add-on's Configuration tab")
    state = state_path(data)
    secrets = auth.SecretFile(state / auth.SECRETS_FILE)
    filled = _check_secrets(opts, mode, secrets)
    password = _check_admin_password(opts)
    text = render_config(opts, ssl_dir)

    for option in filled:  # the operator's options win over secrets saved on /admin
        os.environ[SECRET_OPTIONS[mode][option]] = str(opts[option]).strip()
        if secrets.delete(SECRET_ENTRIES[option]):
            say(f"{option} is set on the Configuration tab; it replaces the one saved on /admin")
    os.environ["XDG_CONFIG_HOME"] = str(data)
    os.environ["XDG_STATE_HOME"] = str(data / "state")
    os.environ.setdefault("PYTHON_KEYRING_BACKEND", "keyring.backends.null.Keyring")
    os.environ["OS2SLICE_ADDON"] = "1"
    os.environ["OS2SLICE_RUNTIME"] = "home-assistant"
    # Not in config.toml: a changed rendering would count as "the options changed" and
    # replace the file, dropping the edits made on /admin. `serve` reads this instead.
    os.environ["OS2SLICE_REDIRECT_PORT"] = str(REDIRECT_PORT)
    _apply_admin_password(password, state / "admin.json", say)
    path = data / "os2slice" / "config.toml"
    _write_config(text, path, bool(opts.get("reset_config")), say)
    return path


def main() -> int:
    try:
        opts = json.loads(OPTIONS.read_text(encoding="utf-8"))
        prepare(opts)
    except (OSError, ValueError, KeyError, OptionsError) as e:
        print(f"os2slice add-on: {e}", file=sys.stderr, flush=True)
        return 1

    from os2slice import cli

    verbose = ["-v"] if opts.get("log_level") == "debug" else []
    cli.main([*verbose, "doctor"])  # the pass/fail table goes to the add-on log
    return cli.main([*verbose, "serve"])


if __name__ == "__main__":
    sys.exit(main())
